### PR TITLE
Feature/alg unit test

### PR DESCRIPTION
**Pull request by SrinivasMushnoori**
PR with testing for selection alg

### CODE REVIEW

**Comment by andre-merzky** [comment]
Hi Srinivas, 

In this PR, we now have two definitions
```sh
$ grep -r select_replicas_1D src/ bin/
src/radical/repex/algorithms.py:def select_replicas_1D(waitlist, criteria, replica):
bin/radical-repex:def select_replicas_1D(waitlist, criteria, replica):
```

Can you clean this up, please?  Also, the unit test seems to fail:

```
tests/test_async/test_async.py::test_select_replicas_1D FAILED
tests/unittests/test_algorithms.py::test_selection_alg FAILED
```

Can you please also have a look at that? I would like to have this PR merged before we do the changes discussed yesterday, otherwise that will create conflicts.  Thanks!

**Comment by andre-merzky** [comment]
Actually, let me do the alg cleanup - but please do look at the failing test, if you don't mind.  Thanks!

**Comment by SrinivasMushnoori** [comment]
Let me have a look at the tests, they passed when I wrote them...I'll get back to you by end of day.

**Comment by SrinivasMushnoori** [comment]
@andre-merzky I looked at the test.
The failure is in line 67 of `test_async.py` as follows:

```
 [ex_list,new_wl] = algorithms.select_replicas_1D(waitlist, criteria, replica) ### This test fails because the algorithm returns 
                                                                                  ### NoneType instead of an empty ex_list.
                                                                                  ### So clearly new_wl is not being generated either  
```
As indicated in the comment there, we expect `select_replicas_1D` [here](https://github.com/radical-cybertools/radical.repex/blob/feature/alg_unit_test/src/radical/repex/algorithms.py#L35) to return an empty list, but it returns `None`. We discussed this over a call last month, and IIRC we decided that this needed a fix. Let me know if we need a review on this.

**Comment by andre-merzky** [comment]
The fix is to do the same as in line 57: `return [], waitlist` - I'll commit that.

**Comment by andre-merzky** [comment]
Done - but alas the test still fails: an invalid replica set is returned.  Can you please check if the alg semantics is as intended?  If you are sure, do you have an suggestion on how to fix the test?

**Comment by SrinivasMushnoori** [comment]
I'm on it. IIRC this test was *intended* to fail, but let me go through properly and verify semantics.

**Comment by SrinivasMushnoori** [comment]
Unit test fixed, passes.

**Comment by SrinivasMushnoori** [comment]
Correct: but also, the asserts in that section look like:
```
    waitlist = [rlist[1], rlist[2], rlist[4]]
    replica = rlist[2]
    old_len = len(waitlist)

    <some more code>

    assert(isinstance(ex_list, list))
    assert(len(ex_list) == 0)
    assert(len(new_wl) == old_len - len(ex_list))
```

As per our discussion earlier, we had decided that i case the waitlist was smaller than needed to start an exchange, we would return an empty list instead of a `NoneType`

We're indeed dealing with a case here where the `waitlist` is *smaller* than necessary, meaning an empty `ex_list` should be returned and the `waitlist` should be returned as is.  

We're asserting that `len(ex_list) == 0` so that removes the necessity to test if a particular replica is in the list. If the replica in question WERE in the list, that assert would fail. 

Does that explain things?

**Comment by andre-merzky** [comment]
Ah, I see - I didn't get that from the diff, sorry.  However, I think you should have *one* set of tests for the algorithm, and then feed different test cases, instead of writing and changing the cases one by one.

For example, instead of
```
def test_sqr():
    assert(sq(0) == 0)
    assert(sqr(1) == 1)
    assert(sqr(2) == 4)
    ...
```

its easier to maintain

```
def test_sqr():
    for i in range(100):
        assert(sqr(i) == i*i)    
```

In our case, there should be a set of assertions which always holds:

```
    assert(isinstance(ex_list, list))
    assert(len(waitlist) == old_len - len(ex_list))
    if ex_list:
        assert(len(ex_list) == criteria['exchange_size'])
        assert(replica in ex_list)

    for r in waitlist:
        assert(r not in ex_list)

    for r in ex_list:
        assert(r not in waitlist)
```

and then you'd feed several different test data sets (waitlist, criterias, active replica) - they all should pass those assertions.  Hope that makes sense?

**Comment by SrinivasMushnoori** [comment]
Makes sense. I'm on it.

**Comment by SrinivasMushnoori** [comment]
Addressed. Please have a look. Apologies for the delay, been working on other projects for the past few days.

**Comment by SrinivasMushnoori** [comment]
Changes made to raise exception when `wl_size>ex_size`
Test passes.

**Pull request merged**
